### ISSUE TITLE
bug in RESTORE mode off --all-ranks option

### ISSUE THREAD

**Issue by calvinhendriks** [Wiimm/wiimms-szs-tools#6]
If i try to restore the query altered by --all-ranks for the patch command, i get an error.

Invalid `all-ranks' mode (option --all-ranks): 'RESTORE'

the command i ran: wstrt patch --all-ranks=RESTORE --test main.dol

**Comment by Wiimm** [comment]
Bug fix: Option --all-ranks accepts keyword RESTORE now. Due to a spelling mistake, only RETORE was recognized so far.
-> https://szs.wiimm.de/changelog.html#r0
