### ISSUE TITLE
linux: Cannot handle WBZ files

### ISSUE THREAD

**Issue by em-eight** [Wiimm/wiimms-szs-tools#9]
Steps: Do any action on WBZ file using wszst

Output:
```
!! wszst: ERROR #76 [CAN'T OPEN FILE]
!!        WU8-DECODE: Can't find autoadd library.
```

**Comment by em-eight** [comment]
The issue was that I hadn't configured the autoadd archive https://szs.wiimm.de/wszst/cmd-autoadd.html

**Comment by Leseratte10** [comment]
As I mentioned on my other post: To convert a WBZ/WU8 file into an SZS file you need to have the autoadd library set up, to tell WSZST where it can find the additional data files not included in the track. See https://szs.wiimm.de/wszst/cmd-autoadd.html
